#!/bin/zsh

# build-in commands and core utilities
alias f1='fg %1'
alias f2='fg %2'
alias f3='fg %3'
alias f4='fg %4'
alias f5='fg %5'
alias df='df -h'
alias f=fg
# alias j=jobs
# alias la='ls -A'
# alias l='ls -CF'
# alias l.='ls -d .*' #ls hidden files
# alias l1='ls -1'
# alias ls='ls -Fh'
alias ls='exa -Fh'
alias la='exa -aglh --group-directories-first --git'
alias l='exa -GF'
alias l.='exa -d .*'
alias ll.='exa -dlg .*'
alias l1='exa -1'
alias ll='exa -glh --group-directories-first --git'
alias c='clear'
alias tmux='tmux -2'

# editors
alias vim='nvim'
alias wiki='nvim -c VimwikiIndex'
alias diary='nvim -c VimwikiMakeDiaryNote'
alias magit='nvim -c MagitOnly'       # manage git folder with magit

# dotfiles
alias dotfiles='cd ~/.dotfiles'

# other
alias r='ranger'
alias open='xdg-open'

if [ "$PACKAGE_MANAGER" = pacman ]; then
  alias u="sudo pacman --sync --refresh --sysupgrade"
fi

# nvm alias for nodejs
alias nvmload='[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
