#!/bin/bash

# Output colors
BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
PINK="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"
NORMAL="\033[0;39m"

help() {
  echo -e "                                                                   $CYAN"
  echo -e " Avaliable commands  for squadbeat senator                       $NORMAL"
}

if [ $# -eq 0 ]; then
    help
fi

$*
